### ISSUE TITLE
"No such file or directory" - Is something missing?

### ISSUE THREAD

**Issue by hamen** [daeken/Benjen#6]
I installed with:
hamen@~/temp/blog > sudo easy_install benjen 

Then:
hamen@~/temp/blog > benjen
Traceback (most recent call last):
  File "/usr/local/bin/benjen", line 9, in <module>
    load_entry_point('Benjen==1.0', 'console_scripts', 'benjen')()
  File "/usr/local/lib/python2.7/dist-packages/Benjen-1.0-py2.7.egg/EGG-INFO/scripts/benjen.py", line 88, in main
    Benjen(*sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/Benjen-1.0-py2.7.egg/EGG-INFO/scripts/benjen.py", line 15, in **init**
    self.config = yaml.load(file('config.yaml'))
IOError: [Errno 2] No such file or directory: 'config.yaml'

If I place your config.yaml in my current blog folder, I get:
hamen@~/temp/blog > benjen
Traceback (most recent call last):
  File "/usr/local/bin/benjen", line 9, in <module>
    load_entry_point('Benjen==1.0', 'console_scripts', 'benjen')()
  File "/usr/local/lib/python2.7/dist-packages/Benjen-1.0-py2.7.egg/EGG-INFO/scripts/benjen.py", line 88, in main
    Benjen(*sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/Benjen-1.0-py2.7.egg/EGG-INFO/scripts/benjen.py", line 21, in **init**
    shutil.copytree('static', self.out)
  File "/usr/lib/python2.7/shutil.py", line 169, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'static'

Am I missing something?

**Comment by daeken** [comment]
You need to set up the directory structure as per the Readme.  Reopen if you continue to have issues.

**Comment by ghost** [comment]
Adding a comment here to remind me to add a command like benjen --create-initial

**Comment by trytuna** [comment]
two ~/Documents/benjen $ mkdir static
two ~/Documents/benjen $ ls
config.yaml entries     static      templates
two ~/Documents/benjen $ benjen
Traceback (most recent call last):
  File "/usr/local/bin/benjen", line 8, in <module>
    load_entry_point('Benjen==1.0', 'console_scripts', 'benjen')()
  File "/Library/Python/2.7/site-packages/Benjen-1.0-py2.7.egg/EGG-INFO/scripts/benjen.py", line 89, in main

  File "/Library/Python/2.7/site-packages/Benjen-1.0-py2.7.egg/EGG-INFO/scripts/benjen.py", line 22, in **init**

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 168, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'static'
two ~/Documents/benjen $ ls
config.yaml entries     templates
two ~/Documents/benjen $

**Comment by trytuna** [comment]
You are kidding me...?!

Why do you delete my benjen directory? This is the point where I quit trying to use such programs.

Over

**Comment by minimalme** [comment]
Hi, I also add some big issues as methanol on Mountain Lion.
After typing "benjen" outside my blog folder, it deleted a lot of folders!
